# baseURL = 'http://localhost:1313'
languageCode = 'nl-nl'
title = 'Federatieve Toegangsverlening'
theme = "ftv"

[params]
    subtitle = 'Standaard voor vertrouwde toegang binnen het Federatief Datastelsel'
    baseDirectory = '/'
    [params.footer]
        title = 'Standaard voor vertrouwde toegang  binnen het Federatief Datastelsel'
    