# baseURL = 'http://localhost:1313'
languageCode = 'nl-nl'
title = 'Federatieve Toegangsverlening'
theme = "ftv"

[params]
#    baseDirectory = '/ftv/'
    baseDirectory = '/'
#  baseDirectory = '{{< param baseDirectory >}}'