baseURL = 'https://federatieve-toegangsverlening-digilab-overheid-n-5d4b9badc9bcfa.gitlab.io/'
languageCode = 'nl-nl'
title = 'Federatieve Toegangsverlening'
theme = "hugo-book"
custom_css = ["css/custom.css"]
