package: api
output: ./generated.go
generate:
  embedded-spec: true
  strict-server: true
  models: true
  chi-server: true
  client: true
import-mapping:
  https://gitlab.com/digilab.overheid.nl/ecosystem/fsc-vwl-api/-/raw/main/spec/openapi.yaml: gitlab.com/digilab.overheid.nl/ecosystem/fsc-vwl-api
