openapi: 3.0.3
info:
  title: Mock BRP public tables API
  description: |-
    This is a mock REST API to expose the publicly available BRP tables 32-61.
  contact:
    email: digilab@vng.nl
  license:
    name: EUPL 1.2
    url: https://eupl.eu/1.2/en/
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1

paths:
  /nationaliteiten:
    get:
      summary: List nationaliteiten (tabel 32)
      description: Returns all nationaliteiten matching the specified filters.
      operationId: findNationaliteit

      parameters:
        - name: codeFrom
          in: query
          description: The minimum Code of the Nationaliteit to search for.
          required: false
          schema:
            type: integer
            format: int32
        - name: codeTo
          in: query
          description: The maximum Code of the Nationaliteit to search for.
          required: false
          schema:
            type: integer
            format: int32
        - $ref: "#/components/parameters/omschrijvingRx"
        - $ref: "#/components/parameters/omschrijvingFrom"
        - $ref: "#/components/parameters/omschrijvingTo"
        - $ref: "#/components/parameters/datumIngangFrom"
        - $ref: "#/components/parameters/datumIngangTo"
        - $ref: "#/components/parameters/datumEindeFrom"
        - $ref: "#/components/parameters/datumEindeTo"

      responses:
        "200":
          $ref: "#/components/responses/NationaliteitenResponse"
        "400":
          $ref: "#/components/responses/BadRequestErrorResponse"

components:
  parameters:
    omschrijvingRx:
      name: omschrijvingRx
      in: query
      description: Regular expression to filter the Omschrijving of the element on.
      required: false
      schema:
        type: string

    omschrijvingFrom:
      name: omschrijvingFrom
      in: query
      description: The minimum Omschrijving of the element to search for.
      required: false
      schema:
        type: string

    omschrijvingTo:
      name: omschrijvingTo
      in: query
      description: The maximum Omschrijving of the element to search for.
      required: false
      schema:
        type: string

    datumIngangFrom:
      name: datumIngangFrom
      in: query
      description: The minimum DatumIngang of the element to search for.
      required: false
      schema:
        type: string
        format: full-date

    datumIngangTo:
      name: datumIngangTo
      in: query
      description: The maximum DatumIngang of the element to search for.
      required: false
      schema:
        type: string
        format: full-date

    datumEindeFrom:
      name: datumEindeFrom
      in: query
      description: The minimum DatumEinde of the element to search for.
      required: false
      schema:
        type: string
        format: full-date

    datumEindeTo:
      name: datumEindeTo
      in: query
      description: The maximum DatumEinde of the element to search for.
      required: false
      schema:
        type: string
        format: full-date

  schemas:
    datumIngang:
      description: Date on which the element becomes valid
      type: string
      format: full-date
      example: "1990-04-01"

    datumEinde:
      description: Date after which the element becomes invalid.
      type: string
      format: full-date
      example: "2020-12-31"

    Error:
      description: The error that occurred while processing this request.
      type: object
      properties:
        message:
          type: string
          example: foo went wrong

    Nationaliteit:
      description: A nationaliteit.
      allOf:
        - type: object
          properties:
            code:
              description: Unique code.
              type: string
              pattern: "^[0-9]{4}$"
              example: "0080"
            omschrijving:
              description: Unique description.
              type: string
              example: "Nederlandse"
            datumIngang:
              $ref: "#/components/schemas/datumIngang"
            datumEinde:
              $ref: "#/components/schemas/datumEinde"
          required:
            - code
            - omschrijving

    AutorisatieRegel:
      description: An autorisatie regel.
      allOf:
        - type: object
          properties:
            versie:
              description: Sequential version number.
              type: integer
              format: int32
              example: "1"
            afnemerIndicatie:
              description: Unique consumer identifier (95.10).
              type: string
              pattern: "^[0-9]{6}$"
              example: "000203"
            afnemerNaam:
              description: Unique consumer name (95.20).
              type: string
              example: "Gemeente Amsterdam"
            aantekening:
              description: Remarks (95.11).
              type: string
            geheimhouding:
              description: Secrecy indicator (95.12).
              type: integer
              format: int32
              example: 1
            verstrekkingsBeperking:
              description: Limited delivery indicator (95.13).
              type: integer
              format: int32
              example: 1
            kindRelatieBeperking:
              description: Limited delivery indicator for child relationship (95.14).
              type: integer
              format: int32
              example: 1
            datumIngang:
              $ref: "#/components/schemas/datumIngang"
            datumEinde:
              $ref: "#/components/schemas/datumEinde"
          required:
            - versie
            - afnemerIndicatie
            - afnemerNaam

  responses:
    EmptyResponse:
      description: Nothing needs to be returned.
      content:
        application/json:
          schema:
            type: object

    BadRequestErrorResponse:
      description: Invalid input supplied.
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: "#/components/schemas/Error"
            required:
              - errors

    GoneErrorResponse:
      description: ID not found (but the route itself is valid).
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: "#/components/schemas/Error"
            required:
              - errors

    NationaliteitenResponse:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/components/schemas/Nationaliteit"
            required:
              - data

    AutorisatieRegelsResponse:
      description: Successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/components/schemas/AutorisatieRegel"
            required:
              - data
