// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	externalRef0 "gitlab.com/digilab.overheid.nl/ecosystem/fsc-vwl-api"
)

// Error The error that occurred while processing this request.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// Nationaliteit defines model for Nationaliteit.
type Nationaliteit struct {
	// Id Code of a nationaliteit.
	Id Code `json:"id"`
}

// Code Code of a nationaliteit.
type Code = string

// QueryNaam defines model for queryNaam.
type QueryNaam = string

// BadRequestErrorResponse defines model for BadRequestErrorResponse.
type BadRequestErrorResponse struct {
	Errors []Error `json:"errors"`
}

// NationaiteitenResponse defines model for NationaiteitenResponse.
type NationaiteitenResponse struct {
	Data []Nationaliteit `json:"data"`
}

// FindNationailteitParams defines parameters for FindNationailteit.
type FindNationailteitParams struct {
	// Naam (part of) the name of a nationaliteit.
	Naam *QueryNaam `form:"naam,omitempty" json:"naam,omitempty"`

	// FSCVWLVerwerkingsActiviteit id of the verwerking type
	FSCVWLVerwerkingsActiviteit *externalRef0.FSCVWLVerwerkingsActiviteit `json:"FSC-VWL-Verwerkings-Activiteit,omitempty"`

	// FSCVWLVerwerkingsSpan transaction uuid of the incoming request
	FSCVWLVerwerkingsSpan *externalRef0.FSCVWLVerwerkingsSpan `json:"FSC-VWL-Verwerkings-Span,omitempty"`

	// FSCVWLSysteem identifier for the system processing the verwerking
	FSCVWLSysteem *externalRef0.FSCVWLSysteem `json:"FSC-VWL-Systeem,omitempty"`

	// FSCVWLVerwerker the party doing the verwerking, this does not have to be the party responsible for the verwerking
	FSCVWLVerwerker *externalRef0.FSCVWLVerwerker `json:"FSC-VWL-Verwerker,omitempty"`

	// FSCVWLVerantwoordelijke the party responsible for the verwerking, this does not have to be the party doing the verwerking itself
	FSCVWLVerantwoordelijke *externalRef0.FSCVWLVerantwoordelijke `json:"FSC-VWL-Verantwoordelijke,omitempty"`
}
