baseURL = 'https://federatieve-toegangsverlening.gitlab.io/'
languageCode = 'nl-nl'
title = 'Federatieve Toegangsverlening APIs'
[params]
  subtitle = 'Een project van VNG Realisatie t.b.v. standaardisering toegangsverlening APIs.'
  [params.contact]
    email = 'info@vng.nl'
